[package]
name = "arbitrary"
version = "0.3.0"
authors = ["Simonas Kazlauskas <arbitrary@kazlauskas.me>", "Brian L. Troutwine <brian@troutwine.us>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/nagisa/rust_arbitrary/"
documentation = "https://docs.rs/arbitrary/"
description = "The Arbitrary trait for generating structured data from unstructured data"

[dependencies]
